2024-11-04 01:13:42,952 - __main__ - ERROR - Ошибка создания engine: invalid literal for int() with base 10: 'postgres'
2024-11-04 01:14:54,344 - __main__ - ERROR - Ошибка создания engine: invalid literal for int() with base 10: 'postgres'
2024-11-04 01:16:45,459 - __main__ - ERROR - Ошибка создания engine: invalid literal for int() with base 10: 'postgres'
2024-11-04 01:20:53,508 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': 'postgres', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:20:53,508 - __main__ - ERROR - Ошибка создания engine: invalid literal for int() with base 10: 'postgres'
2024-11-04 01:23:42,613 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:23:51,060 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:23:54,191 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:23:59,647 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:24:14,537 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:24:17,147 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:26:36,978 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:26:42,272 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:26:47,755 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:26:48,627 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:31:27,588 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:31:30,996 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:31:35,104 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:31:39,304 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:31:40,141 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:34:11,897 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:34:15,116 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:34:18,986 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:34:19,588 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:34:32,479 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:35:57,447 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:01,856 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:10,853 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:13,165 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:16,376 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:21,424 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:29,093 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:33,921 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:39,206 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:40,025 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:44,017 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:52,667 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:36:53,442 - __main__ - INFO - Параметры подключения: {'host': 'localhost', 'port': '6000', 'dbname': 'postgres', 'user': 'postgres', 'password': '123'}
2024-11-04 01:55:54,290 - __main__ - ERROR - Критическая ошибка: [Errno 2] No such file or directory: 'config.yaml'
2024-11-04 01:58:22,118 - __main__ - ERROR - Критическая ошибка: [Errno 2] No such file or directory: 'config.yaml'
2024-11-04 02:07:29,106 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:07:29,369 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:09:03,541 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:09:03,799 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:10:33,613 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:10:33,871 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:10:35,367 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:10:35,600 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:12:26,326 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:12:26,607 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:12:28,351 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:12:28,615 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:14:08,243 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:14:08,488 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:19:35,331 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:19:35,373 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:19:35,757 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:21:12,186 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:21:12,521 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:21:54,132 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:21:54,404 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:26:23,572 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:26:23,820 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:39:48,998 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 02:39:49,254 - __main__ - ERROR - Критическая ошибка: Location must be one of 'main' or 'sidebar' or 'unrendered'
2024-11-04 03:10:07,236 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:10:07,492 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:10:41,795 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:10:42,045 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:11:09,169 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:11:09,416 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:12:19,358 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:12:19,632 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:13:12,073 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:13:12,316 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:14:32,658 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:14:32,929 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:14:58,665 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:14:58,903 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:15:48,868 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:15:49,128 - __main__ - ERROR - Критическая ошибка: Authenticate.login() got multiple values for argument 'location'
2024-11-04 03:17:02,468 - __main__ - ERROR - Критическая ошибка: 'dict' object has no attribute 'login'
2024-11-04 03:19:16,783 - __main__ - ERROR - Критическая ошибка: 'dict' object has no attribute 'login'
